apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  name: hello  
  labels:
    type: application
    family: force
spec:
  deploymentTargets:
    - name: functional-test
      labels:
        purpose: functional-test
        application: greeting
        edge: "true"
      environment: dev
      manifests:
        storage: git
        type: kustomize            
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: dev
        path: ./functional-test
    - name: performance-test
      labels:
        purpose: performance-test
        edge: "false"
        application: greeting
      environment: dev
      manifests:
        storage: git
        type: kustomize            
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: dev
        path: ./performance-test
    - name: int-test
      labels:
        purpose: int-test
        application: greeting
      environment: dev
      manifests:
        storage: git
        type: ansible            
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: dev
        path: ./int-test/install.yml
    - name: uat-test
      labels:
        purpose: uat-test
        application: greeting
      environment: stage
      manifests:
        storage: git
        type: kustomize            
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: stage
        path: ./uat-test    
    - name: edge
      labels:
        purpose: edge
        application: greeting
      environment: prod
      manifests:
        storage: git
        type: kustomize            
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: prod
        path: ./edge                        
    - name: cloud
      labels:
        purpose: cloud
        application: greeting
      environment: prod
      manifests:
        storage: git
        type: kustomize            
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: prod
        path: ./cloud                      
