name: ci

on:
  push:
    branches:
      - main
      - eedorenko/*
  workflow_dispatch:

env:
  IMAGE_REPO: ghcr.io/${{ github.repository }}/${{ vars.APP_NAME }}
  PACKAGE_STORAGE_BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Login to ghcr
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Image Tag
      id: generate_image_tag
      run: |
          VERSION=${{ vars.SEM_VER }}-${{ github.run_number }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV     
    - name: Build and Push to ghcr
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: ${{ env.IMAGE_REPO }}:${{ env.VERSION }}, ${{ env.IMAGE_REPO }}:latest  
    - name: Build debian package
      id: build_debian_package
      run: |
        containerID=$(docker run -dt $IMAGE_REPO:$VERSION)
        docker cp $containerID:/opt/app/sample .
        docker build --platform linux/x86_64 --build-arg  version_string=$VERSION --build-arg binary_name=sample --build-arg deb_package_name=hello-world --build-arg deb_package_description="Hello World Application" -t fpm -f Dockerfile-fpm .
        containerID=$(docker run --platform linux/x86_64 -dt fpm)
        mkdir -p package
        package_name=$APP_NAME-$VERSION.deb
        docker cp $containerID:/deb-package/$package_name ./package/
      env:
        APP_NAME: ${{ vars.APP_NAME }}
    - name: Publish debian package
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: package
        branch: packages
        target-folder: .
        clean: false
    - name: Start CD
      run: |
          gh workflow run cd.yaml -f commit_id="$PROMOTED_COMMIT_ID" -f version="$VERSION"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROMOTED_COMMIT_ID: ${{ github.sha }}

